import { readFileSync, readdirSync, statSync } from "node:fs";
import * as path from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import {
  contextPath,
  goalsPath,
  openQuestionsPath,
  decisionsPath,
  implementationStatusPath,
  specPath,
  auditPath,
  driftPath,
  handoffsDirPath,
} from "./lib/files.js";
import { parseContextPack } from "./engine/contextPack.js";
import { wrapUntrustedContext } from "./lib/promptSafety.js";
import { appendDecision, normalizeDecisionActor } from "./engine/decisions.js";
import { log } from "./lib/logger.js";
import { addNote } from "./lib/notes.js";
import { AGENT_NOTE_TYPES } from "./lib/signals.js";
import type { AgentNoteType } from "./lib/signals.js";

function safeReadFile(filepath: string): string | null {
  try {
    return readFileSync(filepath, "utf-8");
  } catch {
    return null;
  }
}

function latestHandoffJsonPath(): string | null {
  const dir = handoffsDirPath();
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }

  const jsonFiles = entries.filter((f) => f.endsWith(".json"));
  if (jsonFiles.length === 0) return null;

  jsonFiles.sort((a, b) => {
    const aPath = path.join(dir, a);
    const bPath = path.join(dir, b);
    const aTime = statSync(aPath).mtimeMs;
    const bTime = statSync(bPath).mtimeMs;
    return bTime - aTime;
  });

  return path.join(dir, jsonFiles[0]!);
}

async function main(): Promise<void> {
  const server = new McpServer(
    {
      name: "tack-mcp",
      version: "0.1.0",
    },
    {}
  );

  // Intent: high-level purpose and goals, without architecture internals.
  server.registerResource(
    "intent",
    "tack://context/intent",
    {
      title: "Tack Context – Intent",
      description: "High-level North Star, goals, and open questions for this project.",
      mimeType: "text/markdown",
    },
    async (uri: URL) => {
      const parts: string[] = [];

      const context = safeReadFile(contextPath());
      if (context) {
        parts.push("# context.md", "", context.trim(), "");
      }

      const goals = safeReadFile(goalsPath());
      if (goals) {
        parts.push("# goals.md", "", goals.trim(), "");
      }

      const open = safeReadFile(openQuestionsPath());
      if (open) {
        parts.push("# open_questions.md", "", open.trim(), "");
      }

      const decisions = safeReadFile(decisionsPath());
      if (decisions) {
        parts.push("# decisions.md", "", decisions.trim(), "");
      }

      const text =
        parts.length > 0
          ? parts.join("\n").trimEnd()
          : "No context docs found in .tack/.";
      const wrapped = wrapUntrustedContext(text, "tack://context/intent");

      return {
        contents: [
          {
            uri: uri.href,
            text: wrapped,
          },
        ],
      };
    }
  );

  // Facts: implementation status and architecture spec (guardrails).
  server.registerResource(
    "facts",
    "tack://context/facts",
    {
      title: "Tack Context – Facts",
      description: "Binary, source-anchored implementation status and architecture spec.",
      mimeType: "text/markdown",
    },
    async (uri: URL) => {
      const parts: string[] = [];

      const impl = safeReadFile(implementationStatusPath());
      if (impl) {
        parts.push("# implementation_status.md", "", impl.trim(), "");
      }

      const spec = safeReadFile(specPath());
      if (spec) {
        parts.push("# spec.yaml", "", "```yaml", spec.trim(), "```", "");
      }

      const text =
        parts.length > 0
          ? parts.join("\n").trimEnd()
          : "No implementation_status.md or spec.yaml found in .tack/.";
      const wrapped = wrapUntrustedContext(text, "tack://context/facts");

      return {
        contents: [
          {
            uri: uri.href,
            text: wrapped,
          },
        ],
      };
    }
  );

  // Latest handoff JSON: canonical machine-readable summary for agents.
  server.registerResource(
    "handoff-latest",
    "tack://handoff/latest",
    {
      title: "Tack Handoff – Latest",
      description: "Latest handoff JSON generated by `tack handoff`.",
      mimeType: "application/json",
    },
    async (uri: URL) => {
      const jsonPath = latestHandoffJsonPath();
      if (!jsonPath) {
        return {
          contents: [
            {
              uri: uri.href,
              text: JSON.stringify(
                { error: "No handoff JSON files found in .tack/handoffs/." },
                null,
                2
              ),
            },
          ],
        };
      }

      const text = safeReadFile(jsonPath) ?? "";
      return {
        contents: [
          {
            uri: uri.href,
            text,
          },
        ],
      };
    }
  );

  // Recent decisions: last N entries from the parsed context pack.
  server.registerResource(
    "decisions-recent",
    "tack://context/decisions_recent",
    {
      title: "Tack Decisions – Recent",
      description: "Recent architecture and product decisions driving this project.",
      mimeType: "text/markdown",
    },
    async (uri: URL) => {
      const pack = parseContextPack();
      const recent = pack.decisions.slice(-10);
      if (recent.length === 0) {
        const wrappedEmpty = wrapUntrustedContext(
          "No decisions recorded yet in .tack/decisions.md.",
          "tack://context/decisions_recent"
        );
        return {
          contents: [
            {
              uri: uri.href,
              text: wrappedEmpty,
            },
          ],
        };
      }

      const lines: string[] = ["# Recent Decisions", ""];
      for (const d of recent) {
        lines.push(`- [${d.date}] ${d.decision} — ${d.reasoning}`);
      }

      const wrapped = wrapUntrustedContext(lines.join("\n"), "tack://context/decisions_recent");
      return {
        contents: [
          {
            uri: uri.href,
            text: wrapped,
          },
        ],
      };
    }
  );

  // Machine state overview: audit and drift files, for engineering tasks.
  server.registerResource(
    "machine-state",
    "tack://context/machine_state",
    {
      title: "Tack Machine State",
      description: "Raw machine state from _audit.yaml and _drift.yaml.",
      mimeType: "text/markdown",
    },
    async (uri: URL) => {
      const parts: string[] = [];

      const audit = safeReadFile(auditPath());
      if (audit) {
        parts.push("# _audit.yaml", "", "```yaml", audit.trim(), "```", "");
      }

      const drift = safeReadFile(driftPath());
      if (drift) {
        parts.push("# _drift.yaml", "", "```yaml", drift.trim(), "```", "");
      }

      const text =
        parts.length > 0
          ? parts.join("\n").trimEnd()
          : "No _audit.yaml or _drift.yaml found in .tack/.";
      const wrapped = wrapUntrustedContext(text, "tack://context/machine_state");

      return {
        contents: [
          {
            uri: uri.href,
            text: wrapped,
          },
        ],
      };
    }
  );

  // Tools: write-back channels for agents.
  server.registerTool(
    "log_decision",
    {
      description: "Record a decision with reasoning into .tack/decisions.md and the Tack event log.",
      inputSchema: z.object({
        decision: z.string().min(1),
        reasoning: z.string().min(1),
        actor: z.string().optional(),
      }),
    },
    async (args: {
      decision: string;
      reasoning: string;
      actor?: string;
    }) => {
      const decision = args.decision;
      const reasoning = args.reasoning;
      const actor = typeof args.actor === "string" ? args.actor : undefined;

      appendDecision(decision, reasoning);
      log({
        event: "decision",
        decision,
        reasoning,
        actor: normalizeDecisionActor(actor),
      });

      return {
        content: [
          {
            type: "text",
            text: "Decision logged to .tack/decisions.md.",
          },
        ],
      };
    }
  );

  server.registerTool(
    "log_agent_note",
    {
      description: "Append an agent note into .tack/_notes.ndjson for future handoffs.",
      inputSchema: z.object({
        type: z.enum(AGENT_NOTE_TYPES as [AgentNoteType, ...AgentNoteType[]]),
        message: z.string().min(1),
        actor: z.string().optional(),
        related_files: z.array(z.string()).optional(),
      }),
    },
    async (args: {
      type: AgentNoteType;
      message: string;
      actor?: string;
      related_files?: string[];
    }) => {
      const actor = args.actor && args.actor.trim().length > 0 ? args.actor : "user";

      const ok = addNote({
        type: args.type,
        message: args.message,
        actor,
        related_files: args.related_files,
      });

      const text = ok
        ? "Agent note appended to .tack/_notes.ndjson."
        : "Failed to append agent note to .tack/_notes.ndjson.";

      return {
        content: [
          {
            type: "text",
            text,
          },
        ],
      };
    }
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

// eslint-disable-next-line @typescript-eslint/no-floating-promises
main();
