import { readFileSync, readdirSync, statSync } from "node:fs";
import * as path from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server";
// Bun's resolver currently has trouble with the `./server/stdio` export subpath,
// so we import the concrete ESM file path instead.
import { StdioServerTransport } from "@modelcontextprotocol/sdk/dist/esm/server/stdio.js";
import {
  contextPath,
  goalsPath,
  openQuestionsPath,
  decisionsPath,
  implementationStatusPath,
  specPath,
  auditPath,
  driftPath,
  handoffsDirPath,
} from "./lib/files.js";
import { parseContextPack } from "./engine/contextPack.js";

function safeReadFile(filepath: string): string | null {
  try {
    return readFileSync(filepath, "utf-8");
  } catch {
    return null;
  }
}

function latestHandoffJsonPath(): string | null {
  const dir = handoffsDirPath();
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }

  const jsonFiles = entries.filter((f) => f.endsWith(".json"));
  if (jsonFiles.length === 0) return null;

  jsonFiles.sort((a, b) => {
    const aPath = path.join(dir, a);
    const bPath = path.join(dir, b);
    const aTime = statSync(aPath).mtimeMs;
    const bTime = statSync(bPath).mtimeMs;
    return bTime - aTime;
  });

  return path.join(dir, jsonFiles[0]!);
}

async function main(): Promise<void> {
  const server = new McpServer(
    {
      name: "tack-mcp",
      version: "0.1.0",
    },
    {
      capabilities: {
        resources: {},
      },
    }
  );

  // Intent: high-level purpose and goals, without architecture internals.
  server.registerResource(
    "intent",
    "tack://context/intent",
    {
      title: "Tack Context – Intent",
      description: "High-level North Star, goals, and open questions for this project.",
      mimeType: "text/markdown",
    },
    async (uri) => {
      const parts: string[] = [];

      const context = safeReadFile(contextPath());
      if (context) {
        parts.push("# context.md", "", context.trim(), "");
      }

      const goals = safeReadFile(goalsPath());
      if (goals) {
        parts.push("# goals.md", "", goals.trim(), "");
      }

      const open = safeReadFile(openQuestionsPath());
      if (open) {
        parts.push("# open_questions.md", "", open.trim(), "");
      }

      const decisions = safeReadFile(decisionsPath());
      if (decisions) {
        parts.push("# decisions.md", "", decisions.trim(), "");
      }

      const text =
        parts.length > 0
          ? parts.join("\n").trimEnd()
          : "No context docs found in .tack/.";

      return {
        contents: [
          {
            uri: uri.href,
            text,
          },
        ],
      };
    }
  );

  // Facts: implementation status and architecture spec (guardrails).
  server.registerResource(
    "facts",
    "tack://context/facts",
    {
      title: "Tack Context – Facts",
      description: "Binary, source-anchored implementation status and architecture spec.",
      mimeType: "text/markdown",
    },
    async (uri) => {
      const parts: string[] = [];

      const impl = safeReadFile(implementationStatusPath());
      if (impl) {
        parts.push("# implementation_status.md", "", impl.trim(), "");
      }

      const spec = safeReadFile(specPath());
      if (spec) {
        parts.push("# spec.yaml", "", "```yaml", spec.trim(), "```", "");
      }

      const text =
        parts.length > 0
          ? parts.join("\n").trimEnd()
          : "No implementation_status.md or spec.yaml found in .tack/.";

      return {
        contents: [
          {
            uri: uri.href,
            text,
          },
        ],
      };
    }
  );

  // Latest handoff JSON: canonical machine-readable summary for agents.
  server.registerResource(
    "handoff-latest",
    "tack://handoff/latest",
    {
      title: "Tack Handoff – Latest",
      description: "Latest handoff JSON generated by `tack handoff`.",
      mimeType: "application/json",
    },
    async (uri) => {
      const jsonPath = latestHandoffJsonPath();
      if (!jsonPath) {
        return {
          contents: [
            {
              uri: uri.href,
              text: JSON.stringify(
                { error: "No handoff JSON files found in .tack/handoffs/." },
                null,
                2
              ),
            },
          ],
        };
      }

      const text = safeReadFile(jsonPath) ?? "";
      return {
        contents: [
          {
            uri: uri.href,
            text,
          },
        ],
      };
    }
  );

  // Recent decisions: last N entries from the parsed context pack.
  server.registerResource(
    "decisions-recent",
    "tack://context/decisions_recent",
    {
      title: "Tack Decisions – Recent",
      description: "Recent architecture and product decisions driving this project.",
      mimeType: "text/markdown",
    },
    async (uri) => {
      const pack = parseContextPack();
      const recent = pack.decisions.slice(-10);
      if (recent.length === 0) {
        return {
          contents: [
            {
              uri: uri.href,
              text: "No decisions recorded yet in .tack/decisions.md.",
            },
          ],
        };
      }

      const lines: string[] = ["# Recent Decisions", ""];
      for (const d of recent) {
        lines.push(`- [${d.date}] ${d.decision} — ${d.reasoning}`);
      }

      return {
        contents: [
          {
            uri: uri.href,
            text: lines.join("\n"),
          },
        ],
      };
    }
  );

  // Machine state overview: audit and drift files, for engineering tasks.
  server.registerResource(
    "machine-state",
    "tack://context/machine_state",
    {
      title: "Tack Machine State",
      description: "Raw machine state from _audit.yaml and _drift.yaml.",
      mimeType: "text/markdown",
    },
    async (uri) => {
      const parts: string[] = [];

      const audit = safeReadFile(auditPath());
      if (audit) {
        parts.push("# _audit.yaml", "", "```yaml", audit.trim(), "```", "");
      }

      const drift = safeReadFile(driftPath());
      if (drift) {
        parts.push("# _drift.yaml", "", "```yaml", drift.trim(), "```", "");
      }

      const text =
        parts.length > 0
          ? parts.join("\n").trimEnd()
          : "No _audit.yaml or _drift.yaml found in .tack/.";

      return {
        contents: [
          {
            uri: uri.href,
            text,
          },
        ],
      };
    }
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

// eslint-disable-next-line @typescript-eslint/no-floating-promises
main();

